### ISSUE TITLE
Completion fail on var name completion

### ISSUE THREAD

**Issue by Ritooon** [Azakur4/autocomplete-php#50]
When I use completion to autocomplete a variable name, it's not replace by the variable name (Like before) but added.

Example : 

I begin to write  : `"$array"`
It prompt a proposition of completion like `"$arrayBigValues"`
But when I fire "Enter" to accept, it not replace what I type and give this : `"$arrayarrayBigValues"`

**Comment by dstaros** [comment]
I have been experiencing the same exact issue. It seems that the $ sign is omitted from the autocomplete suggestions which is why the entire variable name is added to the end of the typed characters.

After disabling the autocomplete-php package and typing the first few characters of the php variable, the autocomplete suggestions now show the $ sign and replaces the entire typed variable name when clicking enter.

I like the autocomplete-php package, but have to disable it until this gets fixed.

**Comment by tdearborn** [comment]
I have the same problem.  Any suggestions for a workaround or alternate PHP autocomplete package?

**Comment by CptAdamica** [comment]
Please fix it. 

![autocomplete_bug](https://user-images.githubusercontent.com/28780118/36787324-114fb2b6-1c8a-11e8-9c19-6302ed39dcaa.gif)

**Comment by jrgilman** [comment]
Same problem.

![Error](https://i.imgur.com/fmboq0h.gif)

**Comment by Azakur4** [comment]
something probably have change I doesn't update this package for a time I will try review what happen there

**Comment by zb2750031** [comment]
i guess autocomplete-plus changed so you have to provide the prefix for the completion.

this is how I fixed it:

added prefix to buildCompletion call on line 173 and 176
added prefix argument to buildCompletion function on line 181
added replacementPrefix attribute on line 184

provider.coffee:
```
  getVarsCompletions: ({editor, prefix}) ->
    completions = []
    lowerCasePrefix = prefix.toLowerCase()

    if @userSuggestions?
      for userVar in @userSuggestions.user_vars when userVar.text.toLowerCase().indexOf(lowerCasePrefix) is 0
        completions.push(@buildCompletion(userVar, prefix))

    for variable in @completions.variables when variable.text.toLowerCase().indexOf(lowerCasePrefix) is 0
      completions.push(@buildCompletion(variable, prefix))

    completions


  buildCompletion: (suggestion, prefix) ->
    text: suggestion.text
    type: suggestion.type
    replacementPrefix: prefix
    displayText: suggestion.displayText ?= null
    snippet: suggestion.snippet ?= null
    leftLabel: suggestion.leftLabel ?= null
    description: suggestion.description ?= "PHP <#{suggestion.text}> #{suggestion.type}"
    descriptionMoreURL: suggestion.descriptionMoreURL ?= null

```

**Comment by CptAdamica** [comment]
It's work, thank you! :)

**Comment by pitininja** [comment]
Thanks for this fix!

**Comment by Ritooon** [comment]
Man, you're a genius ! Thanks a lot

**Comment by Skalzo** [comment]
Hello, the issue still persists.
I used autocomplete-php 0.3.7.
![Test_Img](http://wt7490.my-gateway.de:12301/img/test_var.gif)

**Comment by CptAdamica** [comment]
Me too.

**Comment by cioroianudenis** [comment]
Still having this issue with autocomplete-php 0.3.7, any fix yet?

**Comment by GalacticSun** [comment]
Any fix yet???

**Comment by cioroianudenis** [comment]
Made a fix for this nasty bug here: https://github.com/Azakur4/autocomplete-php/pull/53
Fix is for autocomplete-php v0.3.7.
Also made a pull request for the changes.
Tested it and it works.
